from __future__ import annotations

import json
import os
import secrets
from pathlib import Path
from typing import Literal

from dotenv import load_dotenv
from fastmcp import FastMCP
from fastmcp.tools.tool import ToolResult
from fastmcp.utilities.types import Image
from mcp.types import Annotations, Icon, TextContent
from starlette.requests import Request
from starlette.responses import FileResponse, HTMLResponse, JSONResponse

from .auth import build_auth
from .service import KnowledgeService


load_dotenv()

PUBLIC_URL = os.getenv("MASIL_PUBLIC_URL", "https://masil-mcp.summit1123.co.kr").rstrip("/")
ICON_PATH = Path(__file__).resolve().parent / "static" / "masil-icon.png"

INSTRUCTIONS = """
MASIL 발표 준비용 근거 서버입니다. 최신 상품 계약과 덱 사실을 먼저 사용하고,
문헌은 allowed_claim과 caveat 범위에서만 사용하세요. 과거 Master Q&A와 변경 이력은
질문 해석·충돌 탐지 재료이며 현재 규칙을 덮어쓰지 않습니다. 최종 답은 짧고 쉬운
문장으로 구성하고 candidate, unresolved, historical 상태를 숨기지 마세요.

사용자가 이 커넥터로 무엇을 할 수 있는지 물으면 connector_guide를 호출하세요. 주제를 이해하거나
Q&A를 준비하려면 먼저 prepare_topic_brief로 현재 입장·근거·경계·미검증 부분을 확인하세요.
실제 질문이 주어졌을 때만 prepare_answer_context로 답변 재료를 가져오세요. forbidden_claims와
must_not_say를 예상 질문 목록으로 바꾸지 마세요. 예상 질문 생성은 사용자가 명시적으로 요청했을 때만
Claude가 하며, 저장된 사실이 아닌 generated by Claude라고 밝히세요.

사용자가 문헌 원문·캡처·이미지를 보여달라고 하면 show_evidence_capture를 먼저 호출하세요.
캡처 ID를 추측하지 말고, 도구가 반환한 display_markdown을 최종 답변에 그대로 포함하세요.
MCP ImageContent가 반환되어도 클라이언트 화면 표시를 보장하지 않으므로 사용자가 확인하기 전에는
이미지가 보인다고 말하지 마세요. compare_claims만으로 캡처를 선택하지 마세요.

미확정 전체를 물으면 list_open_items의 status_filter=unresolved와 total_count를 사용하세요.
items 길이를 전체 개수로 추정하지 마세요. 기본 evidence_scope=stage는 Summary·Appendix의 active
근거만 뜻합니다. qa_only·listed_only는 사용자가 그 범위를 명시적으로 요청했을 때만 사용하세요.
reference_only는 목록·한계 설명용이고 banned 문헌은 사용하지 마세요.
""".strip()


def create_server(*, auth_mode: str | None = None, service: KnowledgeService | None = None) -> FastMCP:
    knowledge = service or KnowledgeService()
    mcp = FastMCP(
        "MASIL Knowledge Studio",
        instructions=INSTRUCTIONS,
        version="0.2.0",
        website_url=PUBLIC_URL,
        icons=[
            Icon(
                src=f"{PUBLIC_URL}/favicon.png",
                mimeType="image/png",
                sizes=["512x512"],
            )
        ],
        auth=build_auth(auth_mode),
        mask_error_details=True,
    )

    @mcp.custom_route("/", methods=["GET"], include_in_schema=False)
    async def landing(_: Request) -> HTMLResponse:
        return HTMLResponse(
            """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>MASIL Knowledge Studio</title>
  <link rel="icon" type="image/png" sizes="512x512" href="/favicon.png">
</head>
<body><h1>MASIL Knowledge Studio</h1><p>Remote MCP knowledge server</p></body>
</html>"""
        )

    @mcp.custom_route("/favicon.png", methods=["GET"], include_in_schema=False)
    @mcp.custom_route("/favicon.ico", methods=["GET"], include_in_schema=False)
    async def favicon(_: Request) -> FileResponse:
        return FileResponse(
            ICON_PATH,
            media_type="image/png",
            headers={"Cache-Control": "public, max-age=86400"},
        )

    @mcp.custom_route("/healthz", methods=["GET"], include_in_schema=True)
    async def healthz(_: Request) -> JSONResponse:
        return JSONResponse({"status": "ok", "service": "masil-mcp", **knowledge.stats()})

    @mcp.custom_route("/evidence/{capture_id}/{token}", methods=["GET"], include_in_schema=False)
    async def evidence_image(request: Request):
        capture_id = request.path_params["capture_id"]
        token = request.path_params["token"]
        try:
            metadata, path = knowledge.capture(capture_id)
        except (KeyError, FileNotFoundError):
            return JSONResponse({"error": "capture not found"}, status_code=404)
        expected = f"{metadata['sha256'][:16]}{path.suffix.lower()}"
        if not secrets.compare_digest(token, expected):
            return JSONResponse({"error": "capture not found"}, status_code=404)
        return FileResponse(
            path,
            media_type=metadata.get("mime_type", "application/octet-stream"),
            headers={
                "Cache-Control": "public, max-age=86400, immutable",
                "Content-Disposition": f'inline; filename="{capture_id}{path.suffix.lower()}"',
                "X-Content-Type-Options": "nosniff",
            },
        )

    def capture_result(
        capture_id: str,
        *,
        allow_supporting: bool = False,
        resolution: dict | None = None,
    ) -> ToolResult:
        metadata, path = knowledge.capture(capture_id)
        if metadata.get("card_status") != "active" and not allow_supporting:
            raise ValueError(
                "This is not active Summary/Appendix evidence. Set allow_supporting=true only when the user explicitly requested qa_only or listed_only material."
            )
        token = f"{metadata['sha256'][:16]}{path.suffix.lower()}"
        display_url = f"{PUBLIC_URL}/evidence/{capture_id}/{token}"
        alt = str(metadata.get("alt") or metadata.get("heading") or capture_id).replace("]", "")
        payload = {
            **metadata,
            "display_url": display_url,
            "display_markdown": f"![{alt}]({display_url})",
            "client_rendering": "not_guaranteed",
            "display_rule": (
                "최종 답변에 display_markdown을 그대로 포함하세요. 사용자가 확인하기 전에는 이미지가 보인다고 단정하지 마세요. "
                "capture_kind=deck이면 문헌 원문이 아니라 덱 발췌임을 밝히고, 잘린 영역을 추론하지 마세요."
            ),
        }
        if resolution:
            payload.update(resolution)
        text = (
            "IMAGE_FOR_USER\n"
            + payload["display_markdown"]
            + "\n\nCAPTURE_DISPLAY_PACKET\n"
            + json.dumps(payload, ensure_ascii=False, indent=2)
            + "\nInclude the Markdown above in the final answer. The MCP image block follows, but client rendering is not guaranteed."
        )
        image = Image(
            path=path,
            annotations=Annotations(audience=["user"], priority=1.0),
        ).to_image_content()
        return ToolResult(
            content=[TextContent(type="text", text=text), image],
            structured_content=payload,
        )

    @mcp.tool(tags={"help"})
    def connector_guide() -> dict:
        """Call when the user asks what MASIL Knowledge Studio can do or how to use it."""
        return {
            "purpose": "고정 답변집이 아니라 발표자가 현재 논리와 근거를 해석하고 Q&A에 대비하도록 재료를 찾는 커넥터입니다.",
            "workflows": [
                {"need": "주제의 현재 입장·근거·경계 이해", "use": "prepare_topic_brief"},
                {"need": "실제 질문에 답할 재료", "use": "prepare_answer_context", "output": "현재 사실·문헌·주의점"},
                {"need": "덱 한 페이지 점검", "use": "get_slide_context"},
                {"need": "문헌 근거와 캡처 표시", "use": "get_evidence 또는 show_evidence_capture"},
                {"need": "현재 구현과 상품 계약 비교", "use": "get_implementation"},
                {"need": "과거 표현과 현재 결론 비교", "use": "compare_claims"},
                {"need": "미확정·후보·가설의 정확한 범위 확인", "use": "list_open_items의 status_filter와 total_count"},
            ],
            "rules": [
                "기본 검색은 현재 사실만 사용합니다.",
                "가드레일을 예상 질문으로 자동 변환하지 않습니다.",
                "예상 질문은 사용자가 요청할 때만 Claude가 생성하며 generated by Claude로 표시합니다.",
                "캡처 ID를 추측하지 않고 문헌 연결을 먼저 확인합니다.",
                "이미지 표시 여부는 사용자가 확인하기 전까지 단정하지 않습니다.",
            ],
        }

    @mcp.tool(tags={"search"})
    def search_knowledge(
        query: str,
        top_k: int = 8,
        scope: Literal["all", "current", "canonical", "slides", "evidence", "supporting", "history"] = "current",
        detail: Literal["compact", "full"] = "compact",
    ) -> dict:
        """Search MASIL with Korean/English BM25 plus Korean character n-grams.

        The default current scope returns answer-safe facts from the final deck
        and current product contract. Use canonical for glossary/guardrail
        records, and all or history only when the user explicitly asks why
        wording changed or requests superseded material.
        """
        return knowledge.search(query, top_k=top_k, scope=scope, detail=detail)

    @mcp.tool(tags={"product"})
    def explain_product_logic(topic: str, detail: Literal["compact", "full"] = "compact") -> dict:
        """Return the current MASIL product contract for a topic.

        It distinguishes product rules, current sandbox parameters, planned
        implementation changes, and validated results.
        """
        return knowledge.explain_product_logic(topic, detail=detail)

    @mcp.tool(tags={"deck"})
    def get_slide_context(page: int, detail: Literal["compact", "full"] = "compact") -> dict:
        """Return claims, caveats, and correction status for a final-deck page (1-9)."""
        if page < 1 or page > 9:
            raise ValueError("page must be between 1 and 9")
        return knowledge.get_slide_context(page, detail=detail)

    @mcp.tool(tags={"evidence"})
    def get_evidence(
        query: str,
        top_k: int = 6,
        include_captures: bool = True,
        usage_scope: Literal["stage", "qa_only", "listed_only", "all"] = "stage",
    ) -> dict:
        """Find exact literature mappings; defaults to active Summary/Appendix evidence only.

        If the user asks to see the source, quotation, screenshot, or deck use,
        prefer show_evidence_capture so lookup and display stay in one verified
        step. Do not substitute a fuzzy or unrelated capture. Use qa_only,
        listed_only, or all only when the user explicitly requests that scope.
        """
        return knowledge.get_evidence(
            query,
            top_k=top_k,
            include_captures=include_captures,
            usage_scope=usage_scope,
        )

    @mcp.tool(tags={"implementation"})
    def get_implementation(topic: str = "점수 Care 할인 생활권") -> dict:
        """Compare the audited current demo implementation with the product contract."""
        return knowledge.get_implementation(topic)

    @mcp.tool(tags={"conflict"})
    def compare_claims(query: str) -> dict:
        """Show current and superseded wording; this tool does not select or display captures."""
        return knowledge.compare_claims(query)

    @mcp.tool(tags={"answer", "preparation"})
    def prepare_topic_brief(topic: str) -> dict:
        """Gather current position, evidence, boundaries, and plain-language material for a topic.

        This tool does not generate likely questions or fixed answers. Never
        reinterpret claim_boundaries as a question list. Use it before answering
        or rehearsing so Claude can understand what the materials actually say.
        """
        return knowledge.prepare_topic_brief(topic)

    @mcp.tool(tags={"answer"})
    def prepare_answer_context(
        question: str,
        language: Literal["ko", "en"] = "ko",
        max_chars: int = 7000,
        evidence_scope: Literal["stage", "qa_only", "listed_only", "all"] = "stage",
    ) -> dict:
        """Build a compact evidence packet so Claude can compose a short Q&A response.

        This intentionally returns answer ingredients instead of a frozen answer.
        """
        if max_chars < 2500 or max_chars > 12000:
            raise ValueError("max_chars must be between 2500 and 12000")
        return knowledge.prepare_answer_context(
            question,
            language=language,
            max_chars=max_chars,
            evidence_scope=evidence_scope,
        )

    @mcp.tool(tags={"gaps"})
    def list_open_items(
        query: str = "미확정 unresolved 검증 필요",
        top_k: int = 20,
        status_filter: Literal[
            "unresolved",
            "pilot_hypothesis",
            "candidate_parameter",
            "planned_not_implemented",
            "all",
        ] = "unresolved",
    ) -> dict:
        """List open product items with exact totals; defaults to unresolved items only.

        Use total_count rather than the number of returned items. Set all only
        when the user also wants pilot hypotheses and candidate parameters.
        """
        return knowledge.list_open_items(query=query, top_k=top_k, status_filter=status_filter)

    @mcp.tool(tags={"evidence", "image"})
    def list_captures(
        query: str = "문헌",
        top_k: int = 20,
        usage_scope: Literal["stage", "qa_only", "listed_only", "all"] = "stage",
    ) -> dict:
        """List exact capture IDs; defaults to active Summary/Appendix evidence only.

        Use qa_only, listed_only, or all only when the user explicitly requests
        those supporting/reference materials. For the complete inventory, set
        top_k=50; the response reports total counts and whether it was truncated.
        """
        return knowledge.list_captures(query=query, top_k=top_k, usage_scope=usage_scope)

    @mcp.tool(tags={"evidence", "image"})
    def show_evidence_capture(
        query: str,
        usage_scope: Literal["stage", "qa_only", "listed_only", "all"] = "stage",
    ) -> ToolResult:
        """Find and display the exact mapped evidence capture for a user's topic.

        Always use this when the user asks to show a source, screenshot, or
        image. It prevents guessed capture IDs and returns both MCP ImageContent
        and exact display_markdown for clients that do not render image blocks.
        """
        resolved = knowledge.resolve_evidence_capture(query, usage_scope=usage_scope)
        capture_id = resolved["capture"]["id"]
        return capture_result(
            capture_id,
            allow_supporting=usage_scope != "stage",
            resolution={
                "query": query,
                "usage_scope": usage_scope,
                "resolution": resolved["resolution"],
                "literature": resolved["literature"],
            },
        )

    @mcp.tool(tags={"evidence", "image"})
    def get_capture_image(capture_id: str, allow_supporting: bool = False) -> ToolResult:
        """Display an already verified exact capture ID; do not use this tool to guess an image."""
        return capture_result(capture_id, allow_supporting=allow_supporting)

    @mcp.tool(tags={"status"})
    def knowledge_status() -> dict:
        """Return corpus counts and fingerprint for deployment diagnostics."""
        return knowledge.stats()

    return mcp


mcp = create_server()


def main() -> None:
    host = os.getenv("MASIL_HOST", "127.0.0.1")
    port = int(os.getenv("MASIL_PORT", "8000"))
    path = os.getenv("MASIL_MCP_PATH", "/mcp")
    mcp.run(
        transport="http",
        host=host,
        port=port,
        path=path,
        stateless_http=False,
        json_response=False,
    )


if __name__ == "__main__":
    main()
